spring:
  datasource:
  url: jdbc:mysql://localhost:3306/java5?useSSL=false
  username: root
  password: khai123
  jpa:
  properties:
  hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  ddl-auto: update
